### ISSUE TITLE
Support for additional file formats

### ISSUE THREAD

**Issue by JacenBoy** [BanGround/BanGround-Player#4]
.mp3 is not the ideal file format for rhythm games. Because .mp3 files store additional metadata in front of the audio, there can be an inconsistent delay before the sound begins. This makes finding the correct offset difficult.

Adding support for using .wav and .ogg files with local beatmaps would solve this issue, as neither of these formats have this issue with the delay. Additionally, .wav has the quality advantage of being lossless.

**Comment by zz5840** [comment]
Thank you for your advise, however, because our online music files are from bestdori which doesn't support ogg, and for local, players generally don't know how to convert file format, it's hard to make ogg a mainly used format.
However, we are developing a rhythm game which use ogg as music format, you can join our discord server https://discord.gg/NPZvXek if it interests you.
Here are some screenshots
![Screenshot_2020-03-05-01-04-35-12_df1e0e0356b5ef7d434e61cbe8a6214c](https://user-images.githubusercontent.com/16662647/75904008-6a908300-5e7d-11ea-90c9-2607be5d9c4c.jpg)
![Screenshot_2020-03-04-16-32-33-28_df1e0e0356b5ef7d434e61cbe8a6214c](https://user-images.githubusercontent.com/16662647/75904040-7714db80-5e7d-11ea-99ed-5f3eb185f971.jpg)
![Screenshot_2020-03-05-01-04-48-03_df1e0e0356b5ef7d434e61cbe8a6214c](https://user-images.githubusercontent.com/16662647/75904069-8005ad00-5e7d-11ea-8a06-a96976c67aea.jpg)
